### ISSUE TITLE
clipper -h with differerent help documentation

### ISSUE THREAD

**Issue by zhangjun-123** [YeoLab/clipper#84] opened 2020-09-06 05:00 UTC
![image](https://user-images.githubusercontent.com/64965509/92318572-e2b04f00-f040-11ea-8ef8-08356a6e5a33.png)
can anyone help？

**Comment by algaebrown** [comment] 2020-09-08 22:22
Duplicate of #82

**Closed by algaebrown** 2020-09-08 22:22 UTC
