### ISSUE TITLE
clipper installation error

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [YeoLab/clipper#75] opened 2019-12-27 09:32 UTC
hello there,
I had an error message while running python setup.py install:

/public/home/shishuo/anaconda4/envs/eclip/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /public/home/shishuo/anaconda4/envs/eclip/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /public/home/shishuo/anaconda4/envs/eclip/include -fPIC -I/public/home/shishuo/anaconda4/envs/eclip/include/python3.7m -c clipper/src/peaksmodule.cc -o build/temp.linux-x86_64-3.7/clipper/src/peaksmodule.o

clipper/src/peaksmodule.cc:26:28: error: cannot convert 'char*' to 'const wchar_t*' for argument '1' to 'void Py_SetProgramName(const wchar_t*)'
   Py_SetProgramName(argv[0]);
                            ^

clipper/src/peaksmodule.cc:92:18: error: 'PyInt_AsLong' was not declared in this scope
       long len = PyInt_AsLong(PyList_GetItem(reads, i));
                  ^~~~~~~~~~~~

clipper/src/peaksmodule.cc:203:37: error: 'PyInt_FromLong' was not declared in this scope
     PyList_SetItem(returnList, cut, PyInt_FromLong(OBS_CUTOFF[cut]));
                                     ^~~~~~~~~~~~~~

clipper/src/peaksmodule.cc: In function 'PyObject* peaks_find_sections(PyObject*, PyObject*)':
clipper/src/peaksmodule.cc:261:31: error: 'PyInt_FromLong' was not declared in this scope
   PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                               ^~~~~~~~~~~~~~

clipper/src/peaksmodule.cc:271:33: error: 'PyInt_FromLong' was not declared in this scope
     PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                                 ^~~~~~~~~~~~~~

clipper/src/peaksmodule.cc:390:34: error: 'PyInt_FromLong' was not declared in this scope
     PyTuple_SetItem(read_loc, 0, PyInt_FromLong(read_start));
                                  ^~~~~~~~~~~~~~

clipper/src/peaksmodule.cc:421:25: error: 'PyInt_AsLong' was not declared in this scope
      long incremented = PyInt_AsLong(jxnCount);
                         ^~~~~~~~~~~~

clipper/src/peaksmodule.cc:456:35: error: 'PyInt_FromLong' was not declared in this scope
     PyList_SetItem(retLengths, i, PyInt_FromLong(lengths[i]));
                                   ^~~~~~~~~~~~~~

clipper/src/peaksmodule.cc:468:36: error: 'PyInt_FromLong' was not declared in this scope
       PyList_SetItem(retWiggle, i, PyInt_FromLong(wiggle[i]));

clipper/src/peaksmodule.cc:471:38: error: 'PyInt_FromLong' was not declared in this scope
     PyList_SetItem(retPos_counts, i, PyInt_FromLong(pos_counts[i]));
                                      ^~~~~~~~~~~~~~

clipper/src/peaksmodule.cc:501:3: error: 'Py_InitModule' was not declared in this scope
   Py_InitModule("peaks", peaks_methods);

Do you have any idea on how to fix this? 
really appreciate your response.
Thanks,
Zhenzhen

**Comment by ernstki** [comment] 2020-06-16 18:08
This appears to be a duplicate of #71.

As you did not specify your Python version, I will assume from the appearance of "3.7" in your error output that you are using Python 3.7.

You will probably want to try again with Python 2.7, as advised in issue #71.

**Comment by algaebrown** [comment] 2020-08-05 19:21
CLIPper is released in python 3.7. This should solve the installation problem. 
https://github.com/YeoLab/clipper/releases/tag/2.0

**Closed by algaebrown** 2020-08-05 19:21 UTC
Labels: upgrade
